### PR TITLE
Dynamodb local refactoring

### PR DESCRIPTION
**Pull request by rustworthy**
Addresses [thread](https://github.com/jonhoo/wewerewondering/pull/179#discussion_r1892567645)

### CODE REVIEW

**Review by jonhoo — APPROVED** [review]
Nice, thank you!

**Comment by jonhoo** [comment]
It looks like this broken release builds?
https://github.com/jonhoo/wewerewondering/actions/runs/12517011390/job/34917078828

**Comment by rustworthy** [comment]
> It looks like this broken release builds? https://github.com/jonhoo/wewerewondering/actions/runs/12517011390/job/34917078828

Let me check

**Comment by jonhoo** [comment]
Ah, I know why. It's because the `struct LiveAskQuestion` can now longer be `#[cfg(debug_assertions)]`. I'll fix.

**Comment by jonhoo** [comment]
It's https://github.com/jonhoo/wewerewondering/pull/179 that broke this, not this PR.

**Comment by rustworthy** [comment]
> It's #179 that broke this, not this PR.



> Ah, I know why. It's because the `struct LiveAskQuestion` can now longer be `#[cfg(debug_assertions)]`. I'll fix.

Neiher `const SEED: &str = include_str!("test.json");`

**Comment by rustworthy** [comment]
Makes sense to not include "test.json" into the binary, rather read it in the runtime if we are in the `debug_assertions` arm?

**Comment by jonhoo** [comment]
Fixed in https://github.com/jonhoo/wewerewondering/pull/193

**Comment by jonhoo** [comment]
Could do that too, although I quite like that the test binaries are location-independent.

**Comment by rustworthy** [comment]
> Could do that too, although I quite like that the test binaries are location-independent.

I love the approach in #193 with splitting into debug_assertions and not(debug_assertions) - easier to reason about.

**Pull request merged**
